{"name": "Verify user is able to login", "status": "failed", "statusDetails": {"message": "Setup failed:\nMaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023FDAF40B60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"}, "start": 1721370963658, "stop": 1721370980361, "uuid": "3b12a3a4-489c-4f62-afed-04536abf8639", "historyId": "ff5330313aca591bc8d421c039b3727f", "fullName": "NanonetsLoginTest.Verify user is able to login", "labels": [{"name": "suite", "value": "NanonetsLoginTest"}, {"name": "framework", "value": "robotframework"}, {"name": "language", "value": "cpython3"}, {"name": "host", "value": "DESKTOP-PVBC1II"}, {"name": "thread", "value": "default-68afc2ac-a503-4be3-97ad-7f0f1a0098c6"}, {"name": "tag", "value": "MUT1"}, {"name": "tag", "value": "UAT"}]}