<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0 (Python 3.12.3 on win32)" generated="2024-07-09T12:41:28.973309" rpa="false" schemaversion="5">
<suite id="s1" name="Suites">
<suite id="s1-s1" name="Login" source="C:\Users\Admin\PycharmProjects\RobotFrameworkAutomation\TestCases\Mobile\Android\Login.robot">
<test id="s1-s1-t1" name="Login Test Case" line="7">
<kw name="Open Bizom Application" owner="BizomLoginKeywords">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-07-09T12:41:33.433077" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000216D99E4410&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg time="2024-07-09T12:41:37.513622" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000216D99E4AD0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg time="2024-07-09T12:41:41.616770" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000216D99E5070&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-07-09T12:41:45.714936" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-07-09T12:41:45.713885" elapsed="0.188551">No application is open</status>
</kw>
<msg time="2024-07-09T12:41:45.904487" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-07-09T12:41:45.905484" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000216D99E5B50&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<arg>${REMOTE_URL}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>appPackage=${APP_PACKAGE}</arg>
<arg>appActivity=${APP_ACTIVITY}</arg>
<arg>automationName=${AUTOMATION_NAME}</arg>
<arg>autoGrantPermissions=${AUTO_GRANT_PERMISSIONS}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://appium.io/docs/en/2.1/cli/args/
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-07-09T12:41:29.312732" elapsed="16.594747">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000216D99E5B50&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</kw>
<arg>${REMOTE_URL}</arg>
<arg>${PLATFORM_NAME}</arg>
<arg>${DEVICE_NAME}</arg>
<arg>${APP_PACKAGE}</arg>
<arg>${APP_ACTIVITY}</arg>
<arg>${AUTOMATION_NAME}</arg>
<arg>${AUTO_GRANT_PERMISSIONS}</arg>
<status status="FAIL" start="2024-07-09T12:41:29.312732" elapsed="16.595744">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000216D99E5B50&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</kw>
<kw name="Click multiple times for env to appear and select staging environment" owner="BizomLoginKeywords">
<status status="NOT RUN" start="2024-07-09T12:41:45.908476" elapsed="0.000000"/>
</kw>
<kw name="Enter User name and password" owner="BizomLoginKeywords">
<arg>${email}</arg>
<arg>${pass}</arg>
<status status="NOT RUN" start="2024-07-09T12:41:45.909474" elapsed="0.000000"/>
</kw>
<kw name="Click login Button" owner="BizomLoginKeywords">
<status status="NOT RUN" start="2024-07-09T12:41:45.909474" elapsed="0.000000"/>
</kw>
<kw name="Close Bizom Application" owner="BizomLoginKeywords">
<status status="NOT RUN" start="2024-07-09T12:41:45.909474" elapsed="0.000000"/>
</kw>
<doc>Open and Close Bizom Application</doc>
<status status="FAIL" start="2024-07-09T12:41:29.311732" elapsed="16.597742">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000216D99E5B50&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</test>
<status status="FAIL" start="2024-07-09T12:41:29.078774" elapsed="16.831697"/>
</suite>
<status status="FAIL" start="2024-07-09T12:41:29.062818" elapsed="16.850154"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Suites">Suites</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Login">Suites.Login</stat>
</suite>
</statistics>
<errors>
<msg time="2024-07-09T12:41:33.433077" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000216D99E4410&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg time="2024-07-09T12:41:37.513622" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000216D99E4AD0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg time="2024-07-09T12:41:41.616770" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000216D99E5070&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg time="2024-07-09T12:41:45.904487" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
